# Components prefixed CB are for callback hyperparameter settings

__package_info__:
  package: utime
  version: 2.0.0

CB_tb: &TB
  # tensorboard
  nickname: tb
  class_name: TensorBoard
  kwargs: {log_dir: ./tensorboard, profile_batch: 0}

CB_es: &ES
  # Early stopping
  nickname: es
  class_name: EarlyStopping
  kwargs: {monitor: val_dice, min_delta: 0, patience: 200, verbose: 1, mode: max}

CB_mcp: &MCP
  # Model checkpoint
  nickname: mcp
  class_name: ModelCheckpoint
  kwargs: {filepath: './model/@epoch_{epoch:02d}_val_dice_{val_dice:.5f}.weights.h5',
    monitor: val_dice, save_best_only: false, save_weights_only: true, verbose: 
      1, mode: max}

CB_timer: &TIMER
  # Train timer callback
  nickname: timer
  class_name: TrainTimer
  pass_logger: true
  kwargs: {verbose: true}

CB_csv: &CSV
  # keras.CSVLogger
  nickname: csv
  class_name: CSVLogger
  kwargs: {filename: logs/training.csv, separator: ',', append: true}

CB_mtt: &MTT
  # Max training time callback
  nickname: mtt
  class_name: MaxTrainingTime
  kwargs: {max_minutes: 2800}

datasets:
  # Add dataset IDs --> relative paths here

  #### Training datasets
  shhs: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/shhs.yaml
  chat: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/chat.yaml
  cfs: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/cfs.yaml
  sof: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/sof.yaml
  mros: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/mros.yaml
  ccshs: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/ccshs.yaml
  mesa: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/mesa.yaml
  hpap: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/hpap.yaml
  abc: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/abc.yaml
  phys: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/phys.yaml
  dcsm: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/dcsm.yaml
  sedf_sc: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/sedf_sc.yaml
  sedf_st: 
    /home/lht444/U-Sleep-Keras-3.0/u-sleep-keras3/hyperparameters/dataset_configurations/preprocessed/sedf_st.yaml

  #### Testing datasets
  # isruc_sg1: dataset_configurations/isruc_sg1.yaml
  # isruc_sg2: dataset_configurations/isruc_sg2.yaml
  # isruc_sg3: dataset_configurations/isruc_sg3.yaml
  # svuh: dataset_configurations/svuh.yaml
  # dod_o: dataset_configurations/dod_o.yaml
  # dod_h: dataset_configurations/dod_h.yaml
  # mass_c1: dataset_configurations/mass_c1.yaml
  # mass_c3: dataset_configurations/mass_c3.yaml

build:
  #
  # Hyperparameters passed to the Model.build and __init__ methods
  #
  model_class_name: USleep
  activation: elu
  depth: 12
  kernel_size: 9
  dilation: 1
  transition_window: 1
  complexity_factor: 1.67
  n_classes: 5
  l2_reg:
  batch_shape:
  - 32
  - 35
  - 3840
  - 2

augmenters:
  # On-the-fly augmentation
  [{cls_name: RegionalErase, kwargs: {min_region_fraction: 0.001, max_region_fraction: 
        0.33, log_sample: true, apply_prob: 0.1}}, {cls_name: ChannelDropout, 
      kwargs: {drop_fraction: 0.5, apply_prob: 0.1}}]

fit:
  # Hyperparameters passed to the Trainer object
  balanced_sampling: true
  use_multiprocessing: false
  channel_mixture: false
  margin: 17

  # Loss function(s)
  loss: [SparseCategoricalCrossentropy]
  # loss_kwargs:  # OBS: passed to all losses
  #   name: my_loss

  # Metric function(s)
  metrics: [SparseCategoricalAccuracy]
  # metric_kwargs:  # OBS: passed to all metrics
  #   name: my_metric

  # Ignore 'out-of-bounds' classes in loss computation (e.g. to ignore 'UNKNOWN'/'MOVEMENT' other rare classes)
  # Comment out or set to Null/False to not ignore any classes
  ignore_out_of_bounds_classes: true

  # Optimization
  batch_size: 32
  n_epochs: 12000
  verbose: true
  optimizer: Adam
  optimizer_kwargs: {learning_rate: 1e-06, amsgrad: true, decay: 0.0, beta_1: 
      0.9, beta_2: 0.999, epsilon: 1e-08, gradient_accumulation_steps: 2}
  scheduler: PolynomialDecaySchedule
  scheduler_kwargs: {initial_learning_rate: 1e-05, decay_steps: 120, end_learning_rate: 1e-07, power: 1.0, step: 'epoch'}

  # Callbacks
  callbacks: [*TB, *MCP, *TIMER, *CSV, *ES, *MTT]
